"""add can_contribute to ApiCustomer

Revision ID: 73c1a2cbd8b2
Revises: f6d783bd14ec
Create Date: 2026-01-01 20:32:08.271427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73c1a2cbd8b2'
down_revision: Union[str, None] = 'f6d783bd14ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy import inspect

def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('api_customers')]
    
    if 'can_approve_skus' not in columns:
        op.add_column('api_customers', sa.Column('can_approve_skus', sa.Boolean(), nullable=True, comment='Permission to approve SKUs into the central catalog (Direct Publish)'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_customers', 'can_approve_skus')
    # ### end Alembic commands ###

